// Site Configuration — Generated by Polaris Point Admin
// Template: salon | Theme: Boutique
window.SITE_CONFIG = {

  // === THEME (Boutique — Sage & Rose) ===
  theme: {
    primary: "#3d5a4c",
    primaryDark: "#2a3f35",
    accent: "#c4988e",
    accentLight: "#d4a89e",
    bg: "#FAF6F0",
    text: "#2c3e34",
    muted: "rgba(44,62,52,.55)",
    fontHeading: "'Cormorant Garamond', serif",
    fontBody: "'DM Sans', sans-serif",
    logoUrl: ""
  },

  // === PAGE META ===
  pageTitle: "Studio Be Salon | CO 80524",
  metaDescription: "Studio Be Salon offers fast, reliable service. Licensed and insured.",

  // === IDENTITY ===
  businessName: "Studio Be Salon",
  businessNameShort: "Studio Be",
  licenseNumber: "",

  // === CONTACT ===
  phone: "(970) 416-0400",
  phoneTelHref: "tel:+19704160400",
  email: "info@example.com",
  emailHref: "mailto:info@example.com",
  address: "15 Old Town Square #131, Fort Collins, CO 80524, USA",
  hours: "Monday: 9:00 AM – 9:00 PM | Tuesday: 9:00 AM – 9:00 PM | Wednesday: 9:00 AM – 9:00 PM | Thursday: 9:00 AM – 9:00 PM | Friday: 9:00 AM – 7:30 PM | Saturday: 9:00 AM – 5:00 PM | Sunday: Closed",

  // === TOPBAR ===
  topbarText: "24/7 Emergency Service Available",

  // === HERO ===
  heroHeadline: "Studio Be Salon",
  heroSubtext: "Licensed & insured salon / barber proudly serving CO 80524 and surrounding areas. Rated 4.8 stars by 1115+ customers. Call today for a free estimate.",
  heroImage: "/api/photo?ref=Ab43m-v8w7HrU0M0j2aLyS-suzU_OJJBIZYudhTP2DC45xOkLi5O1aBGCCBeHOwdJIjhgXokxm_LEFvwSUb_EV-8ShPGhGPLsBubtuwFIztHYDn6WPuaSwCX9tNC8PePez2ktJES8L3sV9B845EmnQEyOiIXZPDWZ4n_kxUX1Z5GHf_Gzil-aqvREaSDw6EZOY1bb-NYwFkiHeGxPsUQ8OJGyy82PUO59zj1ECInkCZDqhulPt7-8A70WHAVKwSRZ36fW1FXZH5kRgB6pTgh_Ut9CWAFRMEjeH9UZ1leVrGBdNKCe9PGdyWunyvt6m32Z5TBmjtCIoVrJhHIkahRX_mkMWTkbip9R1S1rewvouzUzgxvKg1MoZVvQFwMgD4c8FF7_td8Es1fXpwa9BZijwnTszzD3H7b8phdYKAh7P3xv9d77f6lQozaBQPEkr_kZiV_&maxwidth=800",
  heroImageAlt: "Studio Be Salon - professional service",
  heroCta1: "Call (970) 416-0400",
  heroCta2: "Get a Free Estimate",

  // === TRUST BADGES ===
  trustBadge1: "Licensed & Insured",
  trustBadge2: "5-Star Rated",
  trustBadge3: "Locally Owned",
  trustBadge4: "10+ Years Experience",

  // === SERVICES ===
  servicesLabel: "What We Do",
  servicesTitle: "Our Services",

  // === ABOUT ===
  aboutImage: "/api/photo?ref=Ab43m-veP5Ki0cbI2fg9pl5XuZ6JHBpj9fNbkgcrKzZMe-nq0L4cokg0MCdZSMVQKGjaj-XeEQMIlGvrb1vHf16YZ15xjv-0Jz-hvWkXK6ANY6zaY5HNMO6m9yMHfoDMJNKlrO6ApJ2xzKERklqHYicNTPTk3tSfHd1k38MDYNmXrfI8OHqY20T5PvYA-oTafrezT9F-lG3EgDCrY_FfS2pNF7-dUOO701ERT3nJ4bdNNV1G6lwqU2NTXPaPN2s_GJDYRUUTcirUdlbkh3iYZcOgZkVUgqgf0HtNfXIl6NPeM0F3XQ&maxwidth=800",
  aboutImageAlt: "Studio Be Salon team",
  aboutLabel: "Why Choose Us",
  aboutTitle: "CO 80524 Trusts Studio Be",
  aboutText: "Studio Be Salon has been serving CO 80524 with reliable, professional salon / barber services. With a 4.8-star rating from 1115 customers, we take pride in quality work and honest pricing. Every job is treated with care and respect.",

  // === WHY CARDS ===
  why1Title: "Same-Day Service",
  why1Text: "Most calls handled the same day.",
  why2Title: "Upfront Pricing",
  why2Text: "Clear quotes before work starts. No surprise fees.",
  why3Title: "Satisfaction Guaranteed",
  why3Text: "If the problem comes back, so do we.",

  // === REVIEWS ===
  reviewsLabel: "Testimonials",
  reviewsTitle: "What Our Customers Say",
  reviews: [
    {
      text: "Nothing but good stuff to say!!\n\nI was incredibly nervous about dying my hair for the first time ever in my life but Abby made me feel so comfortable! For being so young she is super educated on everything! I love her! She listened to what I wanted and did exactly that! Exceeded expectations. I wanted a cut too but moreso a trim to keep my length and she didn’t take too much off, the perfect amount! I love my new bangs too! Thank you Abby! You grew my confidence in myself and my hair immensely. She is my new hair stylist and I will see her again and again and again!!\n\n((Before and after pictures posted!!)) yikes at the before!! Didn’t realize how bad my hair was!\n\nMuch love!\n-Melany",
      attribution: "Melany Dzoba &middot; 8 months ago",
      rating: 5
    },
    {
      text: "Kayla is truly amazing at what she does. Not just her knowledge on color and cuts (which is amazing), but her ability to hear what you truly want and apply it, is something I’ve never experienced. She listens to your wants, your lifestyle, everything and produces amazing work. I’ve never been more in love with my hair. She made me feel comfortable from my moment I walked in. She’s just the best!",
      attribution: "Bailey Wallen &middot; 2 months ago",
      rating: 5
    },
    {
      text: "My daughter and I have counted ourselves as lucky to have found such a wonderful stylist with Meghan. Over the last 5+ years, she’s become the only person that my daughter (now 18) will ever trust with her hair! She’s an amazing stylist with great instincts, and more importantly, a wonderful human being that we’ve gotten to know a little better with each visit. Almost like a long-lost, super cool aunt to my daughter, someone she can trust and respect who also helps her feel heard and seen. Thank you Meghan, and thank you to all of the staff who go out of their way to make each visit feel luxurious!",
      attribution: "Jillian Gregory &middot; 3 months ago",
      rating: 5
    },
    {
      text: "First time going to Studio Be! The Studio itself is gorgeous and clean! The front desks offers you drinks after check in. I did schedule with  Kaitlyn and she did fantastic! I got a haircut, facial, and a hair treatment! All of the services were so much better than I was expecting! Great place to go!",
      attribution: "Annelise &middot; 2 months ago",
      rating: 5
    },
    {
      text: "I love being in Meghan‘s chair! Not only is she a fantastic stylist with excellent technical skills and product knowledge, she is also a joy to be around. Connecting on an emotional level with your clients is a skill that’s hard to teach, and she has that ability in spades. I love my appointments with Meghan!",
      attribution: "Marti B Bruening &middot; 3 months ago",
      rating: 5
    }
  ],

  // === SERVICE AREA ===
  serviceAreaLabel: "Coverage Area",
  serviceAreaTitle: "Serving CO 80524 & Surrounding Areas",
  serviceAreaText: "",
  serviceAreaImage: "/api/photo?ref=Ab43m-vA9_dJT3RjP2o6czpOglRpvEXtX1Xbc5CS2paN8RDd4YJmMJa-7Ru9iAKtY67ij2Fc8ufsOCPUpDktZZ9gvLf4fa0R_eSeicSJbQ-ZLoDgYKr12-4dubM2wZfePvf1f9Mp6VzugkQ_XqiD30-BITSNfEb_6pypOJfKfghc3jlQfUZnIFTojw5p1O5oML1auzxUUNFjXSnEX8Fp6LlKSDEdAEkb7NOo_GPg05zvBY4n6nuLlean7DtBTbdtzpeOLBoLVfqtuuVShOKTYBAExBrkw600licGC8XIMnNfR99rBw&maxwidth=800",
  serviceAreaImageAlt: "Serving CO 80524",
  serviceAreas: ["CO 80524"],

  // === CONTACT FORM ===
  contactLabel: "Get In Touch",
  contactTitle: "Request Your Free Estimate",
  contactText: "Fill out the form and we will get back to you within 2 hours during business hours.",
  formServiceOptions: ["Other"],

  // === CTA BANNER ===
  ctaTitle: "Need Help Right Now?",
  ctaText: "Our team is available to help you today.",
  ctaButton: "Call (970) 416-0400",

  // === FOOTER ===
  footerDescription: "Studio Be Salon. Licensed, insured, and committed to getting the job done right.",
  footerLegal: "&copy; 2026 Studio Be Salon. All rights reserved.",
  footerServices: [],

  // === FEATURE FLAGS ===
  features: {
    mobileNav: true,
    activeNavHighlight: true,
    stickyHeader: true,
    smoothScroll: true,
    formHandling: true,
    scrollReveal: true,
    reviewCarousel: true,
    googleReviewsBadge: true,
    floatingButtons: true,
    stickyBottomCta: true,
    exitIntent: true,
    urgencyBanner: true,
    faqAccordion: true,
    serviceAreaMap: true,
    lightbox: true,
    teamModals: false,
    blogPreview: true,
    cookieConsent: true,
    trustBar: true,
    analytics: false
  },

  // === GOOGLE REVIEWS ===
  googleReviewsRating: "4.8",
  googleReviewsCount: "1115",
  googleReviewsUrl: "https://maps.google.com/?cid=9039226626625593514",

  // === ENGAGEMENT ===
  smsNumber: "9704160400",
  whatsappNumber: "",
  calcomUrl: "",

  exitIntent: {
    headline: "Wait — Get $50 Off Your First Service",
    text: "Book your service today and save. New customers only.",
    cta: "Claim My Discount",
    ctaUrl: "#contact"
  },

  urgencyBanner: {
    text: "Limited Time Offer — Call today for a free estimate",
    endDate: "2026-12-31"
  },

  // === FAQ ===
  faqs: [
  ],

  // === SERVICE AREA MAP ===
  googleMapsEmbed: "https://www.google.com/maps?q=15%20Old%20Town%20Square%20%23131%2C%20Fort%20Collins%2C%20CO%2080524%2C%20USA&output=embed",

  // === BLOG POSTS ===
  blogPosts: [
  ],

  team: [
  ],

  // === TRUST BAR LOGOS ===
  trustLogos: [
    { src: "", alt: "Licensed & Insured" },
    { src: "", alt: "BBB A+ Rated" },
    { src: "", alt: "Google Guaranteed" }
  ],

  // === SEO ===
  canonicalUrl: "",
  ogImage: "",
  geoRegion: "",
  geoPlacename: "CO 80524",
  geoPosition: "",
  schema: {
    type: "LocalBusiness",
    additionalType: "",
    priceRange: "$$",
    foundingDate: "",
    areaServed: ["CO 80524"],
    openingHours: []
  },

  // === ANALYTICS ===
  analytics: {
    ga4Id: "",
    metaPixelId: "",
    hotjarId: "",
    clarityId: ""
  },

  // === COOKIE CONSENT ===
  cookieConsent: {
    text: "We use cookies to improve your experience and analyze site traffic.",
    acceptButton: "Accept",
    declineButton: "No Thanks",
    privacyUrl: "#"
  },

  // === CHATBOT (disabled — toggle off in builder) ===
  chatbot: { enabled: false },

  // === BRAND VOICE ===
  // Shapes AI-composed copy AND folds into the chatbot system prompt.
  brand: {
    targetCustomer: "",
    differentiators: [],
    voiceNotes: ""
  },

  // === OPS / NOTIFICATIONS (all tiers) ===
  // Lead routing + report recipient. Consumed by /api/site-lead.js
  // and the monthly reporting cron.
  ops: {
    leadEmail: "",
    leadCcEmail: "",
    leadAlertCadence: "instant",
    reportEmail: "",
    ownerNotes: ""
  }
};
